# Data Types in NumPy

Let's learn about NumPy’s data types and explore how they affect memory usage and performance in your arrays.

## 1. Introduction to NumPy Data Types
NumPy arrays are homogeneous, meaning that they can only store elements of the same type. This is different from Python lists, which can hold mixed data types. NumPy supports various data types (also called dtypes), and understanding them is crucial for optimizing memory usage and performance.

# Common Data Types in NumPy:

- int32, int64: Integer types with different bit sizes.

- float32, float64: Floating-point types with different precision.

- bool: Boolean data type.

- complex64, complex128: Complex number types.

- object: For storing objects (e.g., Python objects, strings).

In [3]:
import numpy as np


In [4]:
arr = np.array([23,4,3,23])
arr.dtype # Output: int64 (or int32 depending on the system)

dtype('int32')

## 2. Changing Data Types
You can cast (convert) the data type of an array using the .astype() method. This is useful when you need to change the type for a specific operation or when you want to reduce memory usage.

arr.astype("float64")

In [7]:
arr2 = np.array([23,4,3,23],dtype="float32")
arr2

array([23.,  4.,  3., 23.], dtype=float32)

Downcasting to Save Memory


In [9]:
arr_large = np.array([1000000,2000000,3000000],dtype=np.int64)
arr_small = np.array(arr_large.astype(np.int32))# Downcasting to a smaller dtype
print(arr_large.dtype)
print(arr_small.dtype)
print(arr_large)
print(arr_small)

int64
int32
[1000000 2000000 3000000]
[1000000 2000000 3000000]


## 3. Why Data Types Matter in NumPy
The choice of data type affects:

- Memory Usage: Smaller data types use less memory.

- Performance: Operations on smaller data types are faster due to less data being processed.

- Precision: Choosing the appropriate data type ensures that you don't lose precision (e.g., using float32 instead of float64 if you don't need that extra precision).

In [11]:
# we are checking the size 
arr_large.nbytes

24

In [12]:
arr_small.nbytes 

12

In [13]:
arr_int64 = np.array([1, 2, 3], dtype=np.int64)
arr_int32 = np.array([1, 2, 3], dtype=np.int32)

print(arr_int64.nbytes)  # Output: 24 bytes (3 elements * 8 bytes each)
print(arr_int32.nbytes)  # Output: 12 bytes (3 elements * 4 bytes each)

24
12


## 4. String Data Type in NumPy

Although NumPy arrays typically store numerical data, you can also store strings by using the dtype='str' or dtype='U' (Unicode string) format. However, working with strings in NumPy is less efficient than using lists or Python's built-in string types.

In [15]:
arr = np.array(['apple','banana','mango','orange','grapes'])
print(arr)
print(arr.dtype)

['apple' 'banana' 'mango' 'orange' 'grapes']
<U6


In [16]:
arr = np.array(['apple','banana','mango','orange','grapes'],dtype='U10')# Unicode string array
print(arr)

['apple' 'banana' 'mango' 'orange' 'grapes']


## 5. Complex Numbers

NumPy also supports complex numbers, which consist of a real and imaginary part. You can store complex numbers using complex64 or complex128 data types.

In [18]:
arr = np.array([1+2j,3+4j,5+6j],dtype='complex128')
print(arr)

[1.+2.j 3.+4.j 5.+6.j]


## 6. Object Data Type

If you need to store mixed or complex data types (e.g., Python objects), you can use dtype='object'. However, this type sacrifices performance, so it should only be used when absolutely necessary.

In [20]:
arr = np.array([{'a':1},[1,2,3],'hello'],dtype='object')
print(arr)

[{'a': 1} list([1, 2, 3]) 'hello']


## 7. Choosing the Right Data Type
Choosing the correct data type is essential for:

- Optimizing memory: Using the smallest data type that fits your data.

- Improving performance: Smaller types generally lead to faster operations.

- Ensuring precision: Avoid truncating or losing important decimal places or values.

# Summary:

- NumPy arrays are homogeneous, meaning all elements must be of the same type.

- Use .astype() to change data types and optimize memory and performance.

- The choice of data type affects memory usage, performance, and precision.

- Be mindful of complex numbers and object data types, which can increase memory usage and reduce performance