# 1. Understanding Axes in NumPy
Each dimension in a NumPy array is called an axis. Axes are numbered starting from 0.

For example:

1D array → 1 axis (axis 0)

2D array → 2 axes (axis 0 = rows, axis 1 = columns)

3D array → 3 axes (axis 0 = depth, axis 1 = rows, axis 2 = columns)

Example: Axes in a 2D Array

In [8]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Axis 0 (rows) → Operations move down the columns.

Axis 1 (columns) → Operations move across the rows.

In [10]:
print(np.sum(arr,axis=0))# Sum along rows (down each column)
print(np.sum(arr,axis=1))# Sum along columns (across each row)


[12 15 18]
[ 6 15 24]


# 2. Indexing in Multidimensional Arrays
You can access elements using row and column indices.

In [13]:
print(arr[1,2])    # Row index 1, Column index 2 → Output: 6

6


In [15]:
print(arr[0:2,1:3]) # Extracts first 2 rows and last 2 columns (the overlapping part)

[[2 3]
 [5 6]]


# 3. Indexing in 3D Arrays
For 3D arrays, the first index refers to the "depth" (sheets of data).

In [22]:
arr3D = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3D)
print(arr3D.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [28]:
print(arr3D[0,1,2]) #0th part of array first sheet, 1st row  [ 4  5  6] and its 2nd element 6 -- indexing starts with 0 

6


In [ ]:
print(arr3D[:,0,:]) # both part of array , 0th row and each  elements of column

# 4. Practical Example: Selecting Data Along Axes

 Get all rows of the first column

In [39]:
first_col = arr[:,0]
print(first_col)

[1 4 7]


 Get all rows of the second col 

In [44]:
second_col = arr[:, 1]
print(second_col)

[2 5 8]


first row all col


In [48]:
first_row = arr[0,:]
print(first_row)

[1 2 3]


Second row all col

In [52]:
first_row = arr[1,:]
print(first_row)

[4 5 6]


# 3D array
 Get the first row from each "sheet" in a 3D array

In [55]:
first_rows = arr3D[:,0 ,:]
print(first_rows)

[[1 2 3]
 [7 8 9]]


Get the first col from each "sheet" in a 3D array


In [60]:
first_col = arr3D[:,:,0]
print(first_col)

[[ 1  4]
 [ 7 10]]


# 5. Changing Data Along an Axis
 Replace all elements in column 1 with 0
 

In [66]:
arr[:,1]=0
print(arr)

[[1 0 3]
 [4 0 6]
 [7 0 9]]


In [70]:
arr[0,:]=0
print(arr)

[[0 0 0]
 [4 0 6]
 [7 0 9]]


In [74]:
arr[1,:]=7
print(arr)

[[0 0 0]
 [7 7 7]
 [7 0 9]]


 Replace all elements in column 1 with 9


In [79]:
arr[:, 1] = 9
print(arr)

[[0 9 0]
 [7 9 7]
 [7 9 9]]


# 6. Summary
Axis 0 = rows (vertical movement), Axis 1 = columns (horizontal movement)

Indexing works as arr[row, column] for 2D arrays and arr[depth, row, column] for 3D arrays

Slicing allows extracting subarrays

Operations along axes help efficiently manipulate data without loops