In [1]:
# using python list 
import numpy as np 
import time 
size = 1_000_000

l1=list(range(size))
l2=list(range(size))
start = time.time()
add = [x+y for x,y in zip(l1,l2)]
print(add[0:10])
end = time.time()

print(end - start )

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
0.1045541763305664


In [2]:
l1 = [1,3,5]
l2 = [2,4,7]
list(zip(l1,l2))

[(1, 2), (3, 4), (5, 7)]

In [3]:
# using numpy array 
import numpy as np 
import time 
size = 1_000_000

l1= np.array(list(range(size)))
l2= np.array(list(range(size)))

start = time.time()
add = l1+l2
end = time.time()
print(add[0:10])


print(end - start )

[ 0  2  4  6  8 10 12 14 16 18]
0.01536250114440918


In [21]:
arr1 = np.array([[1,2,3],[4,5,6]])
print(type(arr))
arr.shape

<class 'numpy.ndarray'>


(2, 3)

In [23]:
import sys

list_data = list(range(1000))
numpy_data = np.array(list_data)

print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")

Python list size: 8056000 bytes
NumPy array size: 4000 bytes


In [29]:
# Python list (loop-based)
list1 = [1,2,3,4,5,6,7,8,9,10]

list_squares = [x ** 2 for x in list1]
print(list_squares)

# NumPy (vectorized)
numpy_squares = arr1 ** 2 # because arr1 is an 2d array thats why the output is also 2d
print(numpy_squares)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
[[ 1  4  9]
 [16 25 36]]
