In [1]:
import numpy as np 
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
flat = arr.flatten()

In [7]:
flat

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
flat[0]

1

In [11]:
flat[3]

4

In [13]:
flat[3:6]

array([4, 5, 6])

In [15]:
flat[:6]# same as flat [0:6]

array([1, 2, 3, 4, 5, 6])

In [17]:
len(flat)

9

In [19]:
flat[3:8]

array([4, 5, 6, 7, 8])

In [21]:
flat[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [23]:
flat[1:9:2]

array([2, 4, 6, 8])

In [25]:
flat[::2]

array([1, 3, 5, 7, 9])

In [27]:
flat

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
b = flat[3:7]

In [31]:
b

array([4, 5, 6, 7])

In [33]:
b[0]=4444444
b

array([4444444,       5,       6,       7])

In [35]:
flat

array([      1,       2,       3, 4444444,       5,       6,       7,
             8,       9])

# Here  numpy returns the same memory location not a copy 

# Slicing returns a view, not a copy! Changes affect the original array.
This might seem counterintuitive since Python lists create copies when sliced. But in NumPy, slicing returns a view of the original array. Both the sliced array and the original array share the same data in memory, so changes in the slice affect the original array.

Why does this happen?

Memory Efficiency: Avoids unnecessary copies, making operations faster and saving memory.
Performance: Enables faster access and manipulation of large datasets without duplicating data.

In [40]:
b = flat[3:7].copy()# this is not slice because we are using copy to get the copy
b

array([4444444,       5,       6,       7])

In [42]:
b[0]= 77777790
b

array([77777790,        5,        6,        7])

In [44]:
flat

array([      1,       2,       3, 4444444,       5,       6,       7,
             8,       9])

# Fancy indexing 



In [50]:
arr = np.array([1,54,23,53,2,3,34,5,6])
arr[[1,4,6]]# fancy indexing ,  we will get the values of selected index 

array([54,  2, 34])

# boolean masking (Filter Data)


In [59]:
# which will follow the conditions

arr[arr>4]

array([54, 23, 53, 34,  5,  6])

In [61]:
arr[arr<45]

array([ 1, 23,  2,  3, 34,  5,  6])

In [63]:
arr = np.array([10,20,30,40,50])
mask = arr>30
print(arr[mask])

[40 50]
