In [10]:
import numpy as np 

In [8]:
!pip install numpy 


In [12]:
# 1D array 
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3],[4,5,6]])
# 2D array 
print(arr1)
print(arr2)



[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [16]:
np.zeros((3,3)) # array filled with zeros 
np.ones((2,4)) # array filled with ones  
np.full((2,2),7)# array filled with 7 
np.eye(4) #identity matrix
np.arange(1,10,2) # [1, 3, 5, 7, 9] (like range)
np.linspace(0,1,5)# [0. 0.25 0.5 0.75 1.] (evenly spaced)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [18]:
arr = np.array([[10, 20, 30],[40, 50, 60]])
print("Shape : ", arr.shape)
print("Size : ", arr.size)
print("Dimentions : ", arr.ndim)
print("Data type : ", arr.dtype)

Shape :  (2, 3)
Size :  6
Dimentions :  2
Data type :  int32


In [20]:
arr = np.array([1,2,3], dtype=np.float32) # explicit type 
print(arr.dtype) # float32
arr_int = arr.astype(np.int32) # convert float to int 
print(arr_int) # [1,2,3]

float32
[1 2 3]


In [22]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape) # (2,3)
reshaped = arr.reshape((3,2))# Change shape
print(reshaped)
flattened = arr.flatten()# Convert 2D → 1D
print(flattened)# [1 2 3 4 5 6]

(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
