# Built in Mathematical Functions in NumPy

Here are some common NumPy methods that are frequently used for statistical and mathematical operations:

- np.mean() – Compute the mean (average) of an array.

- np.mean(arr)

- np.std() – Compute the standard deviation of an array.

- np.std(arr)

- np.var() – Compute the variance of an array.

- np.var(arr)

- np.min() – Compute the minimum value of an array.

- np.min(arr)

- np.max() – Compute the maximum value of an array.

- np.max(arr)

- np.sum() – Compute the sum of all elements in an array.

- np.sum(arr)

- np.prod() – Compute the product of all elements in an array.

- np.prod(arr)

- np.median() – Compute the median of an array.

- np.median(arr)

- np.percentile() – Compute the percentile of an array.

- np.percentile(arr, 50)  # For the 50th percentile (median)

- np.argmin() – Return the index of the minimum value in an array.

- np.argmin(arr)

- np.argmax() – Return the index of the maximum value in an array.

- np.argmax(arr)

- np.corrcoef() – Compute the correlation coefficient matrix of two arrays.

- np.corrcoef(arr1, arr2)

- np.unique() – Find the unique elements of an array.

- np.unique(arr)

- np.diff() – Compute the n-th differences of an array.

- np.diff(arr)

- np.cumsum() – Compute the cumulative sum of an array.

- np.cumsum(arr)

- np.linspace() – Create an array with evenly spaced numbers over a specified interval.

- np.linspace(0, 10, 5)  # 5 numbers from 0 to 10

- np.log() – Compute the natural logarithm of an array.

- np.log(arr)

- np.exp() – Compute the exponential of an array.

- np.exp(arr)

These methods are used for performing mathematical and statistical operations with NumPy



In [2]:
import numpy as np 


In [8]:
arr = np.array([3,5,2,33])


In [10]:
np.mean(arr)

10.75

In [12]:
np.max(arr)


33

In [14]:
np.min(arr)


2

In [16]:
np.std(arr)


12.891373084353738

In [18]:
np.var(arr)


166.1875

In [20]:
np.sum(arr)


43

In [22]:
np.prod(arr)


990

In [24]:
np.median(arr)


4.0

In [26]:
np.percentile(arr,50)# for 5th percentile(median)


4.0

### retrun the index



In [33]:
np.argmin(arr) # return the index of min value in array

2

In [35]:
np.argmax(arr)


3

In [37]:
np.unique(arr)

array([ 2,  3,  5, 33])

In [39]:
np.diff(arr)

array([ 2, -3, 31])

In [41]:
np.cumsum(arr)

array([ 3,  8, 10, 43], dtype=int32)

In [45]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [47]:
np.log(arr)

array([1.09861229, 1.60943791, 0.69314718, 3.49650756])

In [51]:
np.exp(arr)

array([2.00855369e+01, 1.48413159e+02, 7.38905610e+00, 2.14643580e+14])